export const photo = (id: string) => `/uploads/${id}.jpg`;
export const seedProducts = [
  { slug: 'rubashka-iz-hlopka', name: 'Топ без рукавов', category: 'zhenshchinam', price: 18900, oldPrice: 22900, color: 'Молочный', material: '100% хлопок', image: 'photo-1598554747436-c9293d6a588f', description: 'Белый топ без рукавов с лаконичным вырезом. Прямой силуэт легко сочетается с джинсами и свободными брюками. Самостоятельная основа образа или первый слой под жакет.', featured: true },
  { slug: 'bryuki-pryamogo-kroya', name: 'Джоггеры с высокой посадкой', category: 'zhenshchinam', price: 24900, color: 'Пудровый', material: '65% полиэстер, 32% вискоза, 3% эластан', image: 'photo-1594633312681-425c7b97ccd1', description: 'Джоггеры пудрового оттенка с высокой посадкой, поясом и манжетами. Свободная линия бёдер и мягкая ткань позволяют двигаться комфортно весь день.', featured: true },
  { slug: 'myagkiy-dzhemper', name: 'Вязаная накидка', category: 'zhenshchinam', price: 21900, oldPrice: 27900, color: 'Молочный', material: '50% шерсть, 50% акрил', image: 'photo-1434389677669-e08b4cac3105', description: 'Накидка фактурной вязки с V-образным вырезом и бахромой по краю. Свободный силуэт дополнит топ или рубашку в прохладную погоду.', featured: true },
  { slug: 'plate-midi', name: 'Платье макси на запах', category: 'zhenshchinam', price: 29900, color: 'Голубой', material: '70% вискоза, 30% лён', image: 'photo-1539008835657-9e8e9680c956', description: 'Длинное платье на тонких бретелях с V-образным вырезом и поясом. Голубая ткань мягко драпируется; силуэт на запах подходит для летних прогулок и особых встреч.', featured: true },
  { slug: 'zhaket-svobodnogo-kroya', name: 'Бомбер на молнии', category: 'zhenshchinam', price: 36900, color: 'Терракотовый', material: '65% полиэстер, 33% вискоза, 2% эластан', image: 'photo-1591047139829-d91aecb6caea', description: 'Лёгкий бомбер терракотового оттенка с застёжкой на молнию. Эластичные манжеты и аккуратный воротник сохраняют собранный силуэт. Подходит для многослойных сочетаний.', featured: false },
  { slug: 'dzhinsy-straight', name: 'Джинсы Straight', category: 'zhenshchinam', price: 22900, color: 'Синий', material: '99% хлопок, 1% эластан', image: 'photo-1542272604-787c3835535d', description: 'Джинсы прямого кроя из плотного денима. Классическая посадка, пять карманов и немного эластана для комфорта на каждый день.', featured: false },
  { slug: 'trench-gorodskoy', name: 'Городской тренч', category: 'zhenshchinam', price: 49900, color: 'Карамельный', material: '60% хлопок, 40% полиэстер', image: 'photo-1539533018447-63fcce2678e3', description: 'Тренч свободного силуэта с поясом и глубокими карманами. Плотная ткань подходит для прохладных дней; посадку можно регулировать поясом.', featured: false },
  { slug: 'futbolka-plotnyy-hlopok', name: 'Футболка из плотного хлопка', category: 'muzhchinam', price: 8900, color: 'Белый', material: '100% хлопок', image: 'photo-1521572163474-6864f9cf17ab', description: 'Базовая футболка с круглым вырезом и прямым силуэтом. Плотное хлопковое полотно приятно к телу и подходит для многослойных сочетаний.', featured: true },
  { slug: 'rubashka-oxford', name: 'Рубашка с мелким принтом', category: 'muzhchinam', price: 19900, color: 'Голубой', material: '100% хлопок', image: 'photo-1596755094514-f87e34085b2c', description: 'Синяя рубашка с мелким светлым принтом и длинным рукавом. Классический воротник и закруглённый низ дополняют повседневные сочетания с джинсами.', featured: false },
  { slug: 'hudi-bez-printa', name: 'Худи без принта', category: 'muzhchinam', price: 23900, oldPrice: 28900, color: 'Серый меланж', material: '80% хлопок, 20% полиэстер', image: 'photo-1556821840-3a63f95609a7', description: 'Худи с объёмным капюшоном и карманом-кенгуру. Мягкий футер на изнанке согревает в прохладную погоду. Без принтов и лишних деталей.', featured: true },
  { slug: 'dzhinsy-regular', name: 'Джинсы с декоративными деталями', category: 'muzhchinam', price: 24900, color: 'Индиго', material: '100% хлопок', image: 'photo-1541099649105-f69ad21f3246', description: 'Джинсы из синего денима с декоративными потёртостями и нашивками. Зауженный силуэт и выразительные детали для повседневных образов с простой футболкой.', featured: false },
  { slug: 'kurtka-na-molnii', name: 'Куртка на молнии', category: 'muzhchinam', price: 42900, color: 'Чёрный', material: '100% полиуретан; подкладка: 100% полиэстер', image: 'photo-1551028719-00167b16eac5', description: 'Куртка с застёжкой на молнию и боковыми карманами. Гладкая поверхность и чёткая линия плеча создают собранный повседневный образ.', featured: false },
  { slug: 'futbolka-svobodnaya', name: 'Футболка свободного кроя', category: 'muzhchinam', price: 9900, color: 'Чёрный', material: '100% хлопок', image: 'photo-1626596662792-12cdc7ecce71', description: 'Футболка с удлинённым рукавом и спущенной линией плеча. Мягкий хлопок и свободный силуэт для комфортных повседневных сочетаний.', featured: false },
  { slug: 'sumka-na-plecho', name: 'Сумка-конверт', category: 'aksessuary', price: 27900, color: 'Коньячный', material: 'Искусственная кожа; подкладка: полиэстер', image: 'photo-1657603635372-023411921d31', description: 'Компактная сумка-конверт с клапаном для повседневных мелочей. Лаконичная форма и спокойный оттенок легко дополняют городской гардероб.', featured: true },
  { slug: 'gorodskoy-ryukzak', name: 'Городской рюкзак', category: 'aksessuary', price: 18900, color: 'Тёмно-синий', material: '100% полиэстер', image: 'photo-1553062407-98eeb64c6a62', description: 'Лёгкий рюкзак для города и коротких поездок. Основное отделение, внешний карман и регулируемые лямки помогают удобно распределить вещи.', featured: false },
  { slug: 'solntsezashchitnye-ochki', name: 'Солнцезащитные очки', category: 'aksessuary', price: 12900, color: 'Золотистый', material: 'Оправа: металл; линзы: поликарбонат', image: 'photo-1511499767150-a48a237f0083', description: 'Очки в универсальной оправе с мягкими линиями. Лёгкий аксессуар, который завершает повседневный образ. В комплекте мягкий чехол.', featured: false },
];
