import { useEffect, useState, type FormEvent } from 'react';
import { Link, NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, Heart, Menu, Search, ShoppingBag, UserRound, X } from 'lucide-react';
import { useCart, useCategories, useFavorites } from '../shared/api/queries';
import { useAuthStore } from '../shared/store/auth';
import { Toast } from '../shared/ui';
export default function Layout() {
  const {cart}=useCart();const {favorites}=useFavorites();const user=useAuthStore(s=>s.user);const {data:categories}=useCategories();
  const [menuOpen,setMenuOpen]=useState(false);const [search,setSearch]=useState('');const location=useLocation();const navigate=useNavigate();
  useEffect(()=>{setMenuOpen(false);window.scrollTo({top:0});},[location.pathname]);
  const submit=(event:FormEvent)=>{event.preventDefault();navigate(`/search?search=${encodeURIComponent(search.trim())}`);setMenuOpen(false);};
  return <><a className="skip-link" href="#main">Перейти к содержимому</a><div className="announcement"><span>Новый сезон. Больше тебя.</span><Link to="/catalog">Смотреть коллекцию <ArrowRight size={13}/></Link><span className="announcement-location">Казахстан · KZT ₸</span></div>
    <header className="site-header"><div className="header-main container"><button className="icon-button mobile-menu" aria-label={menuOpen?'Закрыть меню':'Открыть меню'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button><Link className="wordmark" to="/" aria-label="FORMA — главная">FORMA</Link><form className="header-search" onSubmit={submit}><Search size={19}/><input aria-label="Поиск товаров" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Найти свою форму"/><button type="submit" aria-label="Найти"><ArrowRight size={19}/></button></form><div className="header-actions"><Link to={user?'/profile':'/login'} className="header-action"><UserRound size={22}/><span>{user?'Кабинет':'Войти'}</span></Link><Link to="/favorites" className="header-action" aria-label={`Избранное, ${favorites.length}`}><span className="counter-icon"><Heart size={22}/>{favorites.length>0&&<b>{favorites.length}</b>}</span><span>Избранное</span></Link><Link to="/cart" className="header-action" aria-label={`Корзина, ${cart.itemCount} товаров`}><span className="counter-icon"><ShoppingBag size={22}/>{cart.itemCount>0&&<b>{cart.itemCount}</b>}</span><span>Корзина</span></Link></div></div>
    <div className={`header-nav-wrap ${menuOpen?'is-open':''}`}><nav className="header-nav container" aria-label="Основное меню"><NavLink to="/catalog" end>Весь каталог</NavLink>{categories?.slice(0,5).map(category=><NavLink key={category.id} to={`/catalog/${category.slug}`}>{category.name}</NavLink>)}<NavLink to="/catalog?sort=newest">Новинки <span className="nav-dot"/></NavLink><NavLink to="/catalog?featured=true" className="nav-featured">Выбор FORMA</NavLink><Link className="nav-right" to="/info/about">О бренде <ArrowRight size={14}/></Link></nav></div></header>
    <main id="main" tabIndex={-1}><Outlet/></main><footer className="site-footer"><div className="container footer-main"><div className="footer-brand"><Link className="wordmark" to="/">FORMA</Link><p>Меньше лишнего.<br/>Больше того, что тебе близко.</p><span className="footer-locale">Казахстан · Цены в тенге</span></div><div><h3>Коллекция</h3><Link to="/catalog">Весь каталог</Link><Link to="/catalog?sort=newest">Новинки</Link><Link to="/catalog?featured=true">Выбор FORMA</Link></div><div><h3>Покупателям</h3><Link to="/info/delivery">Доставка и оплата</Link><Link to="/info/returns">Возврат и отмена</Link><Link to="/info/sizes">Как выбрать размер</Link></div><div><h3>Мой FORMA</h3><Link to="/profile">Личный кабинет</Link><Link to="/profile/orders">Мои заказы</Link><Link to="/favorites">Избранное</Link>{user?.role==='ADMIN'&&<Link to="/admin">Управление магазином</Link>}</div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} FORMA</span><span>Одежда в твоём ритме</span><Link to="/info/privacy">Конфиденциальность</Link></div></footer><Toast/></>;
}
