import { useEffect, type ButtonHTMLAttributes, type ReactNode } from 'react';
import { AlertCircle, ArrowRight, Check, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useToastStore } from './store/shop';
export function Button({className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>) { return <button className={`button ${className}`} {...props}/>; }
export function Price({value,oldPrice}: {value:number;oldPrice?:number|null}) { return <span className="price">{new Intl.NumberFormat('ru-KZ').format(value)} ₸{oldPrice && oldPrice>value ? <del>{new Intl.NumberFormat('ru-KZ').format(oldPrice)} ₸</del>:null}</span>; }
export function Alert({children,success=false}:{children:ReactNode;success?:boolean}) { return <div className={`alert ${success?'success':''}`} role={success?'status':'alert'}>{success?<Check size={18}/>:<AlertCircle size={18}/>}<span>{children}</span></div>; }
export function Loading({label='Загружаем…'}:{label?:string}) { return <div className="loading-state" role="status"><span className="spinner"/>{label}</div>; }
export function ErrorState({error,retry}:{error:Error;retry?:()=>void}) { return <div className="state-panel"><Alert>{error.message}</Alert>{retry&&<Button className="secondary" onClick={retry}>Попробовать снова</Button>}</div>; }
export function EmptyState({title,description,href='/catalog',action='Перейти в каталог'}:{title:string;description:string;href?:string;action?:string}) { return <div className="empty-state"><div className="empty-symbol">F.</div><h2>{title}</h2><p>{description}</p><Link className="button" to={href}>{action}<ArrowRight size={18}/></Link></div>; }
export function Field({label,error,children}:{label:string;error?:string;children:ReactNode}) { return <label className="field"><span>{label}</span>{children}{error&&<span className="field-error">{error}</span>}</label>; }
export function Pagination({page,pages,onChange}:{page:number;pages:number;onChange:(page:number)=>void}) { if(pages<2)return null;return <nav className="pagination" aria-label="Страницы каталога"><button disabled={page<=1} onClick={()=>onChange(page-1)}>Назад</button>{Array.from({length:pages},(_,i)=>i+1).filter(i=>i===1||i===pages||Math.abs(i-page)<=1).map((i,index,array)=><span key={i}>{index>0&&i-array[index-1]>1&&<span className="pagination-gap">…</span>}<button aria-current={i===page?'page':undefined} onClick={()=>onChange(i)}>{i}</button></span>)}<button disabled={page>=pages} onClick={()=>onChange(page+1)}>Далее</button></nav>; }
export function Toast() { const {message,clear}=useToastStore();useEffect(()=>{if(message){const id=setTimeout(clear,4500);return()=>clearTimeout(id);}},[message,clear]);return message?<div className="toast" role="status"><Check size={18}/><span>{message}</span><button aria-label="Закрыть уведомление" onClick={clear}><X size={18}/></button></div>:null; }
export function Breadcrumbs({items}:{items:{label:string;to?:string}[]}) { return <nav className="breadcrumbs" aria-label="Навигационная цепочка"><Link to="/">Главная</Link>{items.map((item,i)=><span key={i}><span aria-hidden="true">/</span>{item.to?<Link to={item.to}>{item.label}</Link>:<span aria-current="page">{item.label}</span>}</span>)}</nav>; }
export const statusLabels:Record<string,string>={PENDING:'Ожидает подтверждения',PROCESSING:'Собираем заказ',PAID:'Оплачен',SHIPPED:'В пути',DELIVERED:'Доставлен',CANCELLED:'Отменён'};
