import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Minus, Plus, Trash2 } from 'lucide-react';
import { useCart } from '../shared/api/queries';
import { useAuthStore } from '../shared/store/auth';
import { Alert, Breadcrumbs, EmptyState, ErrorState, Loading, Price } from '../shared/ui';
export default function CartPage(){const {cart,isLoading,error:loadError,refetch,setQuantity,remove}=useCart();const user=useAuthStore(s=>s.user);const [busy,setBusy]=useState('');const [error,setError]=useState('');
  async function change(id:string,quantity?:number){setBusy(id);setError('');try{if(quantity===undefined)await remove(id);else await setQuantity(id,quantity);}catch(err){setError((err as Error).message);}finally{setBusy('');}}
  return <div className="container page-space"><Breadcrumbs items={[{label:'Корзина'}]}/><div className="page-title-row"><h1>Твоя корзина<span className="heading-dot">.</span></h1><span className="muted">{cart.itemCount} товаров</span></div>{isLoading?<Loading/>:loadError?<ErrorState error={loadError} retry={()=>refetch()}/>:!cart.items.length?<EmptyState title="Здесь пока пусто" description="Самое время найти вещь, которая станет любимой."/>:<>{error&&<Alert>{error}</Alert>}<div className="cart-layout"><section className="cart-items" aria-label="Товары в корзине">{cart.items.map(item=><article className="cart-item" key={item.id}><Link className="cart-item-image" to={`/product/${item.product.slug}`}><img src={item.product.images[0]?.url} alt={item.product.name}/></Link><div className="cart-item-info"><span className="eyebrow muted">{item.product.category.name}</span><Link to={`/product/${item.product.slug}`}><h2>{item.product.name}</h2></Link><p>Цвет: {item.variant.color} <span>·</span> Размер: {item.variant.size}</p><Price value={item.unitPrice}/><div className="quantity-control"><button aria-label={`Уменьшить количество ${item.product.name}`} disabled={!!busy||item.quantity<=1} onClick={()=>change(item.id,item.quantity-1)}><Minus size={15}/></button><span>{item.quantity}</span><button aria-label={`Увеличить количество ${item.product.name}`} disabled={!!busy||item.quantity>=Math.min(item.variant.stock,99)} onClick={()=>change(item.id,item.quantity+1)}><Plus size={15}/></button></div></div><div className="cart-item-total"><Price value={item.total}/><button className="icon-button" aria-label={`Удалить ${item.product.name} из корзины`} disabled={!!busy} onClick={()=>change(item.id)}><Trash2 size={19}/></button></div></article>)}<Link to="/catalog" className="text-link"><ArrowLeft size={17}/>Продолжить покупки</Link></section><aside className="order-summary"><h2>Ваш заказ</h2><div className="summary-line"><span>Товары ({cart.itemCount})</span><Price value={cart.subtotal}/></div><div className="summary-line"><span>Доставка</span><span>При оформлении</span></div><div className="summary-total"><span>Итого</span><Price value={cart.subtotal}/></div><Link className="button" to={user?'/checkout':'/login?redirect=/checkout'}>Перейти к оформлению<ArrowRight size={18}/></Link><p>Оплата при получении.<br/>Стоимость доставки рассчитаем на следующем шаге.</p>{!user&&<p>Войдите или создайте аккаунт, чтобы оформить заказ и следить за доставкой.</p>}</aside></div></>}</div>;
}
