import { useEffect, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Search, SlidersHorizontal, X } from 'lucide-react';
import { api } from '../shared/api/client';
import { useCategories } from '../shared/api/queries';
import type { Page, Product } from '../shared/types';
import { Breadcrumbs, EmptyState, ErrorState, Pagination } from '../shared/ui';
import { ProductGrid, ProductSkeleton } from '../components/ProductCard';
export default function CatalogPage(){
  const {category}=useParams();const [params,setParams]=useSearchParams();const {data:categories}=useCategories();const [search,setSearch]=useState(params.get('search')??'');const [filtersOpen,setFiltersOpen]=useState(false);
  const selectedCategory=categories?.find(item=>item.slug===category);const title=selectedCategory?.name??(params.has('search')?'Результаты поиска':params.get('featured')==='true'?'Выбор FORMA':'Каталог одежды');
  function update(key:string,value:string){setParams(current=>{const next=new URLSearchParams(current);if(value)next.set(key,value);else next.delete(key);if(key!=='page')next.delete('page');return next;});}
  useEffect(()=>{setSearch(params.get('search')??'');},[params.get('search')]);
  useEffect(()=>{if(search===(params.get('search')??''))return;const timeout=setTimeout(()=>update('search',search.trim()),350);return()=>clearTimeout(timeout);},[search]);
  const query=new URLSearchParams(params);if(category)query.set('category',category);query.set('limit','12');const products=useQuery({queryKey:['products',query.toString()],queryFn:({signal})=>api<Page<Product>>(`/products?${query}`,{signal})});
  const activeFilters=['minPrice','maxPrice','inStock','featured'].filter(key=>params.has(key));
  return <div className="container catalog-page"><Breadcrumbs items={[{label:'Каталог',to:category?'/catalog':undefined},...(category?[{label:selectedCategory?.name??category}]:[])]}/><div className="page-title-row"><div><span className="eyebrow muted">НАЙДИ ТО, ЧТО ТЕБЕ БЛИЗКО</span><h1>{title}<span className="heading-dot">.</span></h1></div><span className="muted">{products.data?`${products.data.total} товаров`:'Коллекция FORMA'}</span></div>
    <div className="catalog-layout"><aside className={`catalog-sidebar ${filtersOpen?'open':''}`}><div className="filter-mobile-heading"><h2>Фильтры</h2><button className="icon-button" onClick={()=>setFiltersOpen(false)} aria-label="Закрыть фильтры"><X/></button></div><h2>Категории</h2><nav className="category-list" aria-label="Фильтр по категории"><Link className={!category?'selected':''} to={`/catalog?${params}`}>Вся одежда</Link>{categories?.map(item=><Link className={category===item.slug?'selected':''} key={item.id} to={`/catalog/${item.slug}?${new URLSearchParams([...params].filter(([key])=>key!=='page'))}`}>{item.name}{item.productCount!==undefined&&<span>{item.productCount}</span>}</Link>)}</nav><div className="filter-group"><h2>Цена, ₸</h2><div className="price-filters"><label><span>От</span><input aria-label="Минимальная цена" type="number" min="0" value={params.get('minPrice')??''} placeholder="0" onChange={e=>update('minPrice',e.target.value)}/></label><span>—</span><label><span>До</span><input aria-label="Максимальная цена" type="number" min="0" value={params.get('maxPrice')??''} placeholder="150 000" onChange={e=>update('maxPrice',e.target.value)}/></label></div></div><div className="filter-group"><label className="checkbox-label"><input type="checkbox" checked={params.get('inStock')==='true'} onChange={e=>update('inStock',e.target.checked?'true':'')}/>Только в наличии</label><label className="checkbox-label"><input type="checkbox" checked={params.get('featured')==='true'} onChange={e=>update('featured',e.target.checked?'true':'')}/>Выбор FORMA</label></div>{activeFilters.length>0&&<button className="reset-link" onClick={()=>setParams(params.get('search')?{search:params.get('search')!}:{})}>Сбросить фильтры<X size={15}/></button>}<div className="sidebar-note"><span>F.</span><p>Не знаешь свой размер?</p><Link to="/info/sizes">Поможем выбрать <ArrowIcon/></Link></div></aside>
    <section className="catalog-results" aria-label="Товары"><div className="catalog-toolbar"><label className="catalog-search"><Search size={18}/><input aria-label="Поиск по каталогу" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Название или описание"/>{search&&<button aria-label="Очистить поиск" onClick={()=>{setSearch('');update('search','');}}><X size={16}/></button>}</label><button className="filter-toggle" onClick={()=>setFiltersOpen(!filtersOpen)} aria-expanded={filtersOpen}><SlidersHorizontal size={18}/><span>Фильтры</span></button><label className="sort-select"><span>Сначала:</span><select aria-label="Сортировка товаров" value={params.get('sort')??'newest'} onChange={e=>update('sort',e.target.value)}><option value="newest">Новинки</option><option value="popular">Популярные</option><option value="price_asc">Дешевле</option><option value="price_desc">Дороже</option></select></label></div>{products.isLoading?<ProductSkeleton count={6}/>:products.error?<ErrorState error={products.error} retry={()=>products.refetch()}/>:products.data?.items.length?<><ProductGrid products={products.data.items}/><Pagination page={products.data.page} pages={products.data.pages} onChange={page=>{update('page',String(page));window.scrollTo({top:180,behavior:'smooth'});}}/></>:<EmptyState title="Ничего не нашлось" description="Попробуйте другое название или измените фильтры."/>}</section></div></div>;
}
function ArrowIcon(){return <span aria-hidden="true">↗</span>;}
