import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { ArrowRight, Check, ShieldCheck } from 'lucide-react';
import { api } from '../shared/api/client';
import { useCart } from '../shared/api/queries';
import { useAuthStore } from '../shared/store/auth';
import type { Address, Order, ShippingMethod } from '../shared/types';
import { addressSchema } from '../shared/validation';
import { Alert, Breadcrumbs, Button, EmptyState, ErrorState, Loading, Price } from '../shared/ui';
import AddressFields from '../components/AddressFields';
export default function CheckoutPage(){
  const {cart,isLoading,error:cartError}=useCart();const user=useAuthStore(s=>s.user);const navigate=useNavigate();const client=useQueryClient();const [shippingId,setShippingId]=useState('');const [error,setError]=useState('');const key=useRef(crypto.randomUUID());
  const shipping=useQuery({queryKey:['shipping'],queryFn:()=>api<ShippingMethod[]>('/shipping-methods')});const addresses=useQuery({queryKey:['addresses',user?.id],queryFn:()=>api<Address[]>('/users/me/addresses')});
  const {register,handleSubmit,reset,formState:{errors,isSubmitting}}=useForm<Address>({resolver:zodResolver(addressSchema),defaultValues:{name:user?.name??'',phone:user?.phone??'',city:'',street:'',postalCode:''}});
  const method=shipping.data?.find(item=>item.id===shippingId);
  useEffect(()=>{if(shipping.data?.length&&!shippingId)setShippingId(shipping.data[0].id);},[shipping.data,shippingId]);
  async function submit(address:Address){setError('');if(!shippingId){setError('Выберите способ доставки');return;}try{const order=await api<Order>('/orders',{method:'POST',headers:{'Idempotency-Key':key.current},body:{address,shippingMethodId:shippingId,paymentMethod:'COD'}});client.invalidateQueries({queryKey:['cart']});client.invalidateQueries({queryKey:['orders']});client.setQueryData(['order',order.id],order);navigate(`/order-success/${order.id}`,{replace:true});}catch(err){setError((err as Error).message);client.invalidateQueries({queryKey:['cart']});}}
  if(isLoading||shipping.isLoading)return <div className="container"><Loading/></div>;
  if(cartError||shipping.error)return <div className="container page-space"><ErrorState error={(cartError||shipping.error)!}/></div>;
  if(!cart.items.length)return <div className="container"><EmptyState title="В корзине пока пусто" description="Добавьте товары, чтобы перейти к оформлению."/></div>;
  return <div className="container page-space checkout-page"><Breadcrumbs items={[{label:'Корзина',to:'/cart'},{label:'Оформление заказа'}]}/><div className="page-title-row"><h1>Последний штрих<span className="heading-dot">.</span></h1><span className="checkout-secure"><ShieldCheck size={18}/>Безопасное оформление</span></div><form className="checkout-layout" onSubmit={handleSubmit(submit)} noValidate><div><section className="checkout-section"><h2><span>01</span>Куда доставить</h2>{addresses.data&&addresses.data.length>0&&<label className="field"><span>Сохранённый адрес</span><select defaultValue="" onChange={e=>{const address=addresses.data.find(a=>a.id===e.target.value);if(address){const {id:_,...values}=address;reset(values);}}}><option value="">Указать новый адрес</option>{addresses.data.map(address=><option value={address.id} key={address.id}>{address.city}, {address.street}</option>)}</select></label>}<AddressFields register={register} errors={errors}/></section><section className="checkout-section"><h2><span>02</span>Способ доставки</h2>{shipping.data?.length?shipping.data.map(item=><label className={`shipping-option ${shippingId===item.id?'selected':''}`} key={item.id}><input type="radio" name="shipping" checked={shippingId===item.id} onChange={()=>setShippingId(item.id)}/><span><strong>{item.name}</strong><span>{item.description} · {item.estimatedDays}</span></span><Price value={item.price}/></label>):<Alert>Способы доставки пока недоступны. Попробуйте оформить заказ позже.</Alert>}</section><section className="checkout-section"><h2><span>03</span>Оплата</h2><div className="payment-option"><Check size={18}/><div><strong>При получении</strong><p>Заказ создаётся без предварительного списания денег.</p></div></div></section></div><aside className="order-summary checkout-summary"><h2>Твои новые любимые</h2><div className="checkout-items">{cart.items.map(item=><div className="checkout-item" key={item.id}><img src={item.product.images[0]?.url} alt=""/><div><strong>{item.product.name}</strong><span>{item.variant.size} · {item.variant.color} · {item.quantity} шт.</span><Price value={item.total}/></div></div>)}</div><div className="summary-line"><span>Товары</span><Price value={cart.subtotal}/></div><div className="summary-line"><span>Доставка</span>{method?<Price value={method.price}/>:<span>Выберите способ</span>}</div><div className="summary-total"><span>Итого</span><Price value={cart.subtotal+(method?.price??0)}/></div>{error&&<Alert>{error}</Alert>}<Button disabled={isSubmitting||!method}>{isSubmitting?'Оформляем заказ…':'Подтвердить заказ'}<ArrowRight size={18}/></Button><p>Проверьте адрес и состав заказа перед подтверждением.</p></aside></form></div>;
}
export function OrderSuccessPage(){const {id}=useParams();const order=useQuery({queryKey:['order',id],queryFn:()=>api<Order>(`/orders/${id}`)});if(order.isLoading)return <Loading/>;if(order.error)return <div className="container page-space"><ErrorState error={order.error}/></div>;return <div className="container success-page"><div className="success-check"><Check size={34}/></div><span className="eyebrow">СПАСИБО ЗА ВАШ ВЫБОР</span><h1>Уже почти ваши<span className="heading-dot">.</span></h1><p>Заказ <strong>№ {order.data?.number}</strong> принят.<br/>Следите за его статусом в личном кабинете.</p><div className="success-details"><span>К оплате при получении</span><Price value={order.data?.total??0}/><span>{order.data?.address.city}, {order.data?.address.street}</span></div><div className="success-actions"><Link className="button" to="/profile/orders">Мои заказы<ArrowRight size={18}/></Link><Link className="button secondary" to="/catalog">Продолжить покупки</Link></div></div>;}
