import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Box, RefreshCcw, ShieldCheck } from 'lucide-react';
import { api } from '../shared/api/client';
import { useCategories } from '../shared/api/queries';
import type { Page, Product } from '../shared/types';
import { ProductGrid, ProductSkeleton } from '../components/ProductCard';
import { ErrorState } from '../shared/ui';
export default function HomePage(){
  const {data:categories}=useCategories();const products=useQuery({queryKey:['products','home'],queryFn:()=>api<Page<Product>>('/products?featured=true&limit=8&sort=newest')});
  const popular=useQuery({queryKey:['products','popular'],queryFn:()=>api<Page<Product>>('/products?limit=4&sort=popular&inStock=true')});
  return <div className="container home-page"><section className="hero"><div className="hero-content"><span className="eyebrow"><span/> НОВАЯ КОЛЛЕКЦИЯ · 2026</span><h1>Твоя форма.<br/>Твои правила.</h1><p>Простые вещи. Свободные силуэты.<br/>Гардероб, который подстраивается под тебя.</p><Link to="/catalog" className="button">Смотреть коллекцию<ArrowRight size={20}/></Link><div className="hero-bottom"><span>НА КАЖДЫЙ ДЕНЬ.<br/>С ХАРАКТЕРОМ.</span><span className="hero-page">01 <span>/ 01</span></span></div></div><div className="hero-visual"><img src="/uploads/photo-1626596662792-12cdc7ecce71.jpg" alt="Свободный повседневный образ из новой коллекции FORMA" fetchPriority="high"/><span className="hero-image-label">EVERYDAY / ESSENTIALS</span><Link to="/catalog" className="hero-image-link" aria-label="Перейти к новой коллекции"><ArrowUpRight size={25}/></Link></div></section>
    <nav className="category-strip" aria-label="Категории одежды"><Link className="category-pill active" to="/catalog">Вся одежда<ArrowUpRight size={17}/></Link>{categories?.map(category=><Link className="category-pill" key={category.id} to={`/catalog/${category.slug}`}>{category.name}</Link>)}</nav>
    <section className="home-products"><div className="section-heading"><div><span className="eyebrow muted">СОБЕРИ СВОЙ ГАРДЕРОБ</span><h2>В центре внимания<span className="heading-dot">.</span></h2></div><Link className="text-link" to="/catalog?featured=true">Смотреть всё <ArrowRight size={18}/></Link></div>{products.isLoading?<ProductSkeleton count={8}/>:products.error?<ErrorState error={products.error} retry={()=>products.refetch()}/>:products.data?.items.length?<ProductGrid products={products.data.items}/>:<p className="muted">Коллекция скоро появится. Загляните в полный каталог.</p>}</section>
    <section className="brand-note"><span className="eyebrow">ПРОСТО БЫТЬ СОБОЙ</span><h2>Хорошая база.<br/><span>Бесконечно твоя.</span></h2><p>Мы собираем вещи, которые легко сочетаются друг с другом. Спокойные цвета, удобный крой и внимание к деталям — чтобы каждое утро начиналось проще.</p><Link to="/info/about" className="text-link">Знакомство с FORMA<ArrowUpRight size={18}/></Link><div className="brand-watermark" aria-hidden="true">F.</div></section>
    <section className="home-products"><div className="section-heading"><h2>Популярное<span className="heading-dot">.</span></h2><Link className="text-link" to="/catalog?sort=popular">Весь каталог <ArrowRight size={18}/></Link></div>{popular.isLoading?<ProductSkeleton count={4}/>:popular.error?<ErrorState error={popular.error} retry={()=>popular.refetch()}/>:popular.data?.items.length?<ProductGrid products={popular.data.items}/>:<p className="muted">Товары появятся здесь после пополнения коллекции.</p>}</section>
    <section className="benefits" aria-label="О покупках"><Link to="/info/delivery"><Box size={26}/><div><h3>Ближе, чем кажется</h3><p>Доставка по Казахстану</p></div><ArrowUpRight size={18}/></Link><Link to="/info/returns"><RefreshCcw size={25}/><div><h3>Всё под контролем</h3><p>Управление заказом в кабинете</p></div><ArrowUpRight size={18}/></Link><Link to="/info/delivery"><ShieldCheck size={26}/><div><h3>Оплата при получении</h3><p>Стоимость известна заранее</p></div><ArrowUpRight size={18}/></Link></section>
  </div>;
}
